---

variables:
  DEBIAN_FRONTEND: 'noninteractive'
  COMPOSER_ALLOW_SUPERUSER: 1
  COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.cache/composer"
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.cache/npm"
  CI_BUILD_DIR: '/tmp/plugin'
  MOODLE_BRANCH: 'MOODLE_35_STABLE'
  MOODLE_START_BEHAT_SERVERS: 'no'
  DB: 'mysqli'
  DB_NAME: 'moodle'
  DB_HOST: 'db'
  CIVER: '^4'

default:
  services:
    - name: 'mysql:5.7'
      alias: 'db57'
      command:
        - '--character-set-server=utf8mb4'
        - '--collation-server=utf8mb4_unicode_ci'
        - '--innodb_file_per_table=On'
        - '--wait-timeout=28800'
        - '--skip-log-bin'
      variables:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_INITDB_SKIP_TZINFO: 'yes'
    - name: 'mysql:8.0'
      alias: 'db'
      command:
        - '--character-set-server=utf8mb4'
        - '--collation-server=utf8mb4_unicode_ci'
        - '--innodb_file_per_table=On'
        - '--wait-timeout=28800'
        - '--skip-log-bin'
      variables:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_INITDB_SKIP_TZINFO: 'yes'
  cache:
    paths:
      - .cache
  before_script:
    - mkdir -pv "$CI_BUILD_DIR"
    - cp -ru "$CI_PROJECT_DIR/"* "$CI_BUILD_DIR"
    - apt-get -yq update
    - apt-get -yq install --no-install-suggests --no-install-recommends git ca-certificates curl mariadb-client
    - 'curl -sS https://raw.githubusercontent.com/creationix/nvm/v0.39.7/install.sh | bash'
    - . ~/.bashrc
    - nvm install -b --default --no-progress lts/gallium
    - 'curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer'
    - composer create-project -n --no-dev --no-progress --no-ansi moodlehq/moodle-plugin-ci /opt/mci $CIVER
    - export PATH="/opt/mci/bin:/opt/mci/vendor/bin:$PATH"
    - moodle-plugin-ci install --db-host="$DB_HOST" --db-name="$DB_NAME" --no-init

Moodle 3.5, PHP 7.1, MySQL 5.7:
  image: 'moodlehq/moodle-php-apache:7.1'
  variables:
    CIVER: '^3'
    DB_HOST: 'db57'
  script:
    - moodle-plugin-ci phplint
    - moodle-plugin-ci codechecker
    - moodle-plugin-ci validate
    - moodle-plugin-ci phpdoc

Moodle 3.9, PHP 7.2, MySQL 5.7:
  image: 'moodlehq/moodle-php-apache:7.2'
  variables:
    CIVER: '^3'
    DB_HOST: 'db57'
    MOODLE_BRANCH: 'MOODLE_39_STABLE'
  script:
    - moodle-plugin-ci phplint
    - moodle-plugin-ci codechecker
    - moodle-plugin-ci validate
    - moodle-plugin-ci phpdoc

Moodle 4.1, PHP 7.4, MySQL 8.0:
  image: 'moodlehq/moodle-php-apache:7.4'
  variables:
    MOODLE_BRANCH: 'MOODLE_401_STABLE'
  script:
    - moodle-plugin-ci phplint
    - moodle-plugin-ci codechecker
    - moodle-plugin-ci validate
    - moodle-plugin-ci phpdoc

Moodle 4.3, PHP 8.0, MySQL 8.0:
  image: 'moodlehq/moodle-php-apache:8.0'
  variables:
    MOODLE_BRANCH: 'MOODLE_403_STABLE'
  script:
    - moodle-plugin-ci phplint
    - moodle-plugin-ci codechecker
    - moodle-plugin-ci validate
    - moodle-plugin-ci phpdoc
