---

definitions:
  installscript: &baseInstall
    export DEBIAN_FRONTEND=noninteractive ;
    export COMPOSER_ALLOW_SUPERUSER=1 ;
    apt-get -q update &&
    apt-get -yq --no-install-suggests --no-install-recommends install git ca-certificates mysql-client curl &&
    echo '[client]' > ~/.my.cnf ; echo 'default-authentication-plugin=mysql_native_password' >> ~/.my.cnf &&
    curl -sS https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash &&
    . ~/.bashrc &&
    nvm install -b --default --no-progress lts/carbon && 
    curl -sS https://getcomposer.org/installer | php -- --install-dir='/usr/local/bin' --filename='composer' &&
    { [ -z "${CIVER}" ] && export CIVER='^4' ; } ;
    cd "$BITBUCKET_CLONE_DIR/.." ;
    composer create-project -n --no-dev --no-progress --prefer-dist moodlehq/moodle-plugin-ci ci $CIVER &&
    { [ -z "${MOODLE_BRANCH}" ] && export MOODLE_BRANCH='MOODLE_35_STABLE' ;
    echo "MOODLE_BRANCH=$MOODLE_BRANCH" ; } ;
    export TRAVIS_BUILD_DIR="$BITBUCKET_CLONE_DIR" ;
    export PATH="$BITBUCKET_CLONE_DIR/../ci/bin:$BITBUCKET_CLONE_DIR/../ci/vendor/bin:$PATH" ;
    export COMPOSER_CACHE_DIR='/root/.composer/cache' &&    
    moodle-plugin-ci install --db-type=mysqli --db-user=root --db-host='127.0.0.1' --no-init
  services:
    mysql:
      image: 'mysql:8.0'
      variables:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_INITDB_SKIP_TZINFO: 'yes'
  caches:
    npm:
      path: "$HOME/.npm"

pipelines:
  default:
    - parallel:
        steps:
        - step:
            name: 'Moodle 3.5, PHP 7.1 and MariaDB 10.4'
            image: 'moodlehq/moodle-php-apache:7.1'
            services:
              - 'mysql'
            caches:
              - 'composer'
              - 'npm'
            script:
              - export CIVER='^3'
              - *baseInstall
              - moodle-plugin-ci phplint
              - moodle-plugin-ci codechecker
              - moodle-plugin-ci validate
              - moodle-plugin-ci savepoints
              - moodle-plugin-ci phpdoc
        - step:
            name: 'Moodle 3.9, PHP 7.2 and MariaDB 10.4'
            image: 'moodlehq/moodle-php-apache:7.2'
            services:
              - 'mysql'
            caches:
              - 'composer'
              - 'npm'
            script:
              - export CIVER='^3'
              - export MOODLE_BRANCH='MOODLE_39_STABLE'
              - *baseInstall
              - moodle-plugin-ci phplint
              - moodle-plugin-ci codechecker
              - moodle-plugin-ci validate
              - moodle-plugin-ci savepoints
              - moodle-plugin-ci phpdoc
        - step:
            name: 'Moodle 4.1, PHP 7.4 and MariaDB 10.4'
            image: 'moodlehq/moodle-php-apache:7.4'
            services:
              - 'mysql'
            caches:
              - 'composer'
              - 'npm'
            script:
              - export MOODLE_BRANCH='MOODLE_401_STABLE'
              - *baseInstall
              - moodle-plugin-ci phplint
              - moodle-plugin-ci codechecker
              - moodle-plugin-ci validate
              - moodle-plugin-ci savepoints
              - moodle-plugin-ci phpdoc
        - step:
            name: 'Moodle 4.3, PHP 8.0 and MariaDB 10.6'
            image: 'moodlehq/moodle-php-apache:8.0'
            services:
              - 'mysql'
            caches:
              - 'composer'
              - 'npm'
            script:
              - export MOODLE_BRANCH='MOODLE_403_STABLE'
              - *baseInstall
              - moodle-plugin-ci phplint
              - moodle-plugin-ci codechecker
              - moodle-plugin-ci validate
              - moodle-plugin-ci savepoints
              - moodle-plugin-ci phpdoc
